### PR TITLE
Install cli with pip

### LINKED ISSUE #33: Enable CLI installation via pip
Over at **stac-rs** I used a separate Python package (https://pypi.org/project/stacrs/ and https://pypi.org/project/stacrs-cli/) and I _think_ we should do the same here, since the CLI is [a separate crate](https://github.com/developmentseed/cql2-rs/tree/main/cli). So that'd be `cql2-cli` on PyPI.

### PR DESCRIPTION
**Pull request by gadomski**
## What I am changing

- Add the ability to install the CLI from PyPI (not just cargo)

## How I did it

- Refactored the CLI code so we had a lib to use from Python
- Broke the main lib (again) to remove `Error::BoonCompile`, which wasn't `Send` and therefore couldn't be used with **anyhow**. Not a big deal because the only place that error variant was used is on validator instantiation, and the cql2 json-schema should never ship broken.
- Had to do a quick backflip to stop Python from grabbing an interrupt during (e.g.) typing on standard input, 🙇🏼 https://github.com/PyO3/pyo3/issues/3218
- Added `--version` to CLI, forgot to do that before

## How you can test it

```shell
$ maturin develop -m python/Cargo.toml --uv 1>/dev/null 2>/dev/null && which cql2 && cql2 --version
/Users/gadomski/Code/developmentseed/cql2-rs/.venv/bin/cql2
cql2-cli 0.1.0
```

## Related Issues

- Closes #33 
- Depends on #36 because I update the docs

### CODE REVIEW

**Comment by kylebarron** [comment]
> * Depends on [Add docs #36](https://github.com/developmentseed/cql2-rs/pull/36) because I update the docs

In the case when you have other PRs that are built on an initial PR, I find it easiest to review if you set the other branch as the target of this PR. Then we can start to review, and the target branch changes automatically to main when you merge the underlying base PR.

**Review by bitner — APPROVED** [review]

**Comment by gadomski** [comment]
> In the case when you have other PRs that are built on an initial PR, I find it easiest to review if you set the other branch as the target of this PR. Then we can start to review, and the target branch changes automatically to main when you merge the underlying base PR.

Cool, thanks! Yeah wasn't sure what The Practice was around these parts 🤠

**Comment by kylebarron** [comment]
I don't think it's "the practice" I think it's just me, and you don't have to follow me 😄

**Comment by gadomski** [comment]
Oh no worries, I chronically under-use github features so often break workflows without even knowing.

**Pull request merged**
